config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "store#home"
    get "store/home"
    get "/cart", to: "store#cart"
    post "/cart", to: "store#cart"
    get "/checkout", to: "store#checkout"
    delete "/carts", to: "carts#destroy", as: :delete_cart
    put "/minus_items", to: "minus_items#update", as: :quantity_minus
    put "/plus_items", to: "plus_items#update", as: :quantity_plus

    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registrations#new"
    end

    resources :categories, only: %i(show)
    resources :books, only: %i(index show)
    resources :carts, only: %i(index create)
    resources :orders, except: %i(edit)
    namespace :admin do
      resources :homes
      resources :categories
      resources :products
      resources :orders
      resources :accounts
      resources :books do
        member do
          delete :delete_image_attachment
        end
      end
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  PROPERTIES = [:name, :desc, :nopage, :quantity, :price,
                :publisher_id, :category_id, :term,
                book_authors: [], images: []].freeze

  belongs_to :publisher
  belongs_to :category
  has_many :order_details, dependent: :nullify
  has_many :orders, through: :order_details
  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors
  has_many_attached :images
  has_many :carts, dependent: :destroy

  delegate :name, to: :publisher, prefix: true
  delegate :name, to: :category, prefix: true

  validates :name, presence: true,
    length: {maximum: Settings.max_name}
  validates :desc, presence: true,
    length: {maximum: Settings.max_desc}
  validates :nopage, presence: true,
    numericality: {only_integer: true, greater_than: Settings.zero}
  validates :quantity, presence: true,
    numericality: {only_integer: true, greater_than_or_equal_to: Settings.zero}
  validates :price, presence: true,
    numericality: {only_integer: true, greater_than: Settings.zero}
  validates :images,
            content_type: {
              in: Settings.image_type,
              message: I18n.t("invalid_image_type")
            },
            size: {
              less_than: Settings.image_size.megabytes,
              message: I18n.t("invalid_image_size")
            }

  scope :recent_add, ->{order created_at: :desc}
  scope :load_book_in_category, ->(category_id){where(category_id: category_id)}
  scope :check_order_detail, ->(book_id){where(book_id: book_id)}

  ransack_alias :book, :name_or_desc_or_publisher_name
  ransacker :created_at do
    Arel.sql("date(created_at)")
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < AdminController
  authorize_resource class: false

  before_action :load_book, except: %i(index new create)
  before_action :check_order_details, only: :destroy

  def index
    @search = Book.ransack params[:q]
    @pagy, @books = pagy @search.result,
                         items: Settings.page_items_10
  end

  def show; end

  def new
    @book = Book.new
    @book.book_authors.build
  end

  def create
    @book = Book.new book_params
    insert_to_book_author

    if @book.save
      flash[:success] = t "success"
      redirect_to admin_books_path
    else
      flash.now[:danger] = t "fail"
      render :new
    end
  end

  def edit; end

  def update
    ActiveRecord::Base.transaction do
      book_image_attach

      @book.update! book_params
      handle_success_update_book
    end
  rescue StandardError => e
    handle_exception e
  end

  def destroy
    if @book.destroy
      flash[:success] = t "success"
    else
      flash[:danger] = t "fail"
    end
    redirect_to admin_books_path
  end

  private

  def book_params
    params.require(:book).permit Book::PROPERTIES
  end

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book

    flash[:danger] = t "not_found"
    redirect_to admin_books_path
  end

  def book_image_attach
    @book.images.attach params[:book][:images] if params[:book][:images]
  end

  def insert_to_book_author
    params.dig(:book, :book_authors, :author_id)&.compact_blank!&.each do |val|
      @book.book_authors.build[:author_id] = val
    end
  end

  def handle_success_update_book
    flash[:success] = t "success"
    redirect_to admin_books_path
  end

  def handle_exception _exception
    flash[:danger] = t "error"
    redirect_back fallback_location: admin_books_path
  end

  def check_order_details
    return if @book.order_details.empty?

    flash[:danger] = t "dont_move_book"
    refresh
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @search = Book.ransack params[:q]
    @pagy, @books = pagy @search.result,
                         items: Settings.page_items_10
  end

  def show
    @book = Book.find_by(id: params[:id])
    return if @book

    flash[:danger] = t "not_found"
    redirect_to root_path
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def find_book id
    return @book if (@book = Book.find_by id: id)

    flash[:danger] = t "not_found"
    redirect_to root_url
  end

  def get_authors_by_book
    Book.book_id.authors
  end

  def price_format number
    number_to_currency(number, unit: "VND", delimiter: ".", format: "%n %u",
      precision: Settings.zero)
  end
end

app/views/admin/books/_book.html.erb
<tr>
  <th scope="row"><%= book_counter + 1 %></th>
  <td><%= link_to book.name, [:admin, book] %></td>
  <td>
    <% book.images.each do |image| %>
      <%= image_tag image, class: "img-fluid img-table" %>
    <% end %>
  </td>
  <td><%= book.category_name %></td>
  <td><%= book.quantity %></td>
  <td><%= price_format book.price %></td>
  <td><%= book.publisher_name %></td>
  <td><%= book.authors.pluck(:name).join(" ,") %></td>
  <td>
    <%= link_to t(".edit"), edit_admin_book_path(book),
    class: "btn btn-warning" %>
  <%= link_to t(".delete"), [:admin, book], method: :delete,
      class: "btn btn-danger", data: { confirm: t(".rusure") } %>
  </td>
</tr>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <div class="col-sm">
      <div class="col-9">
        <%= f.label :name, t(".name"), class: "required" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="col-9">
        <%= f.label :desc, t(".description"), class: "required" %>
        <%= f.text_area :desc, class: "form-control" %>
      </div>
      <div class="col-9">
        <%= f.label :nopage, t(".number_of_pages"), class: "required" %>
        <%= f.number_field :nopage, class: "form-control" %>
      </div>
      <div class="col-9">
        <%= f.label :quantity, t(".quantity"), class: "required" %>
        <%= f.number_field :quantity, class: "form-control" %>
      </div>
      <div class="col-9">
        <%= f.label :price, t(".price"), class: "required" %>
        <%= f.number_field :price, class: "form-control" %>
      </div>
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
    <div class="col-sm">
      <div class="col-9">
        <%= f.label :category_id, t(".category"), class: "required" %>
        <%= f.collection_select :category_id, Category.order(:name), :id, :name,
          {include_blank: true}, class: "form-control" %>
      </div>
      <div class="col-9">
        <%= f.fields_for :book_authors do |book_author| %>
          <%= book_author.label :author_id, t(".author"), class: "required" %>
          <%= book_author.select :author_id, Author.pluck(:name, :id),
            {include_blank: false, selected: Author.first&.id},
            class: "author-multiple form-control", multiple: true %>
        <% end %>
      </div>
      <div class="col-9">
        <%= f.label :publisher_id, t(".publisher"), class: "required" %>
        <%= f.collection_select :publisher_id, Publisher.order(:name), :id, :name,
          {include_blank: true}, class: "form-control" %>
      </div>
      <div class="col-9">
        <%= f.label :images, t(".images"), class: "required" %>
        <%= f.file_field :images, class: "form-control", multiple: true %>
        <div class="gallery d-flex"></div>
          <div class="gallery-w d-flex " id="book_show">
            <% if @book.persisted? %>
              <% f.object.images.each do |image| %>
                <div class="d-block mb-4 h-100">
                  <%= image_tag image, {class: "img-fluid img-thumbnail"}%>
                  <%= link_to t(".remove"), delete_image_attachment_admin_book_url(image.id),
                              method: :delete,
                              data: { confirm: t(".sure")},
                              remote: true %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/books/_form_search.html.erb
<%= search_form_for @search, url: admin_books_path, class: "form-inline" do |f| %>
  <div class="form-floating mr-2">
    <%= f.text_field :book_cont, class: "form-control" %><br>
    <label><%= t "info" %></label>
  </div>
  <div class="form-floating mr-2">
    <%= f.number_field :price_gteq, class: "form-control" %><br>
    <label><%= t "price_greater_than" %></label>
  </div>
  <div class="form-floating mr-2">
    <%= f.number_field :price_lteq, class: "form-control" %><br>
    <label><%= t "price_less_than" %></label>
  </div>
  <div class="form-floating mr-2">
    <%= f.date_field :created_at_eq, value: "%Y/%D/%M", class: "form-control" %><br>
    <label><%= t "create_date" %></label>
  </div>
  <%= f.submit t("search"), class: "btn btn-primary search-btn" %>
<% end %>

app/views/admin/books/delete_image_attachment.js.erb
$('#book_show').html(`
  <% @book.images.each do |image| %>
    <div class="d-block mb-4 h-100">
      <%= j image_tag image, {class: "img-fluid img-thumbnail"}%>
      <%= j link_to t(".remove"), delete_image_attachment_admin_book_url(image.id),
              method: :delete,
              data: { confirm: t(".sure")},
              remote: true %>
    </div>
  <% end %>
`);

app/views/admin/books/edit.html.erb
<div class="container">
  <% provide :title, t("update_book") %>
  <% provide :button_text, t("update_book") %>
  <h1><%= t "update_book" %></h1>
  <div class="card-body">
    <div class="form-floating mb-3 ">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/books/index.html.erb
<% provide :title, t("all_book") %>
<div class="container">
  <h1><%= t "all_book" %></h1>

  <%= render "form_search" %>
  <%= link_to t("create"), new_admin_book_path, class: "btn btn-info mt-3" %>

  <hr class="sidebar-divider">
  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col"><%= t ".index" %></th>
        <th scope="col"><%= t ".name" %></th>
        <th scope="col"><%= t ".image" %></th>
        <th scope="col"><%= t ".category" %></th>
        <th scope="col"><%= t ".quantity" %></th>
        <th scope="col"><%= t ".price" %></th>
        <th scope="col"><%= t ".publisher" %></th>
        <th scope="col"><%= t ".author" %></th>
        <th scope="col"><%= t ".action" %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @books %>
    </tbody>
  </table>
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/admin/books/new.html.erb
<div class="container">
  <% provide :title, t("create_book") %>
  <% provide :button_text, t("create") %>
  <h1><%= t "create_book" %></h1>
  <div >
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/show.html.erb
<% provide:title, @book.name %>
<aside class="col">
  <section class="category-info">
    <div class="row">
      <div class="col-2">
        <span>
          <% @book.images.each do |image| %>
            <%= image_tag image, class: "img-fluid img-table" %>
          <% end %>
        </span>
      </div>
      <div class="col-9">
        <h1><%= @book.name %></h1>
        <span><%= t "description" %>: <%= @book.desc %></span>
        <span><%= t "num_of_pages" %>: <%= @book.nopage %></span>
        <span><%= t "quantity" %>: <%= @book.quantity %></span>
        <span><%= t "price" %>: <%= @book.price %></span>
        <span><%= t "category" %>: <%= @book.category_name %></span>
        <span><%= t "publisher" %>: <%= @book.publisher_name %></span>
      </div>
    </div>
    <%= link_to t(".edit"), edit_admin_book_path(@book),
      class: "btn btn-warning" %>
    <%= link_to t(".delete"), [:admin, @book], method: :delete,
      class: "btn btn-danger", data: { confirm: t(".rusure") } %>
  </section>
</aside>