config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "store#home"
    get "store/home"
    get "/cart", to: "store#cart"
    post "/cart", to: "store#cart"
    get "/checkout", to: "store#checkout"
    delete "/carts", to: "carts#destroy", as: :delete_cart
    put "/minus_items", to: "minus_items#update", as: :quantity_minus
    put "/plus_items", to: "plus_items#update", as: :quantity_plus

    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registrations#new"
    end

    resources :categories, only: %i(show)
    resources :books, only: %i(index show)
    resources :carts, only: %i(index create)
    resources :orders, except: %i(edit)
    namespace :admin do
      resources :homes
      resources :categories
      resources :products
      resources :orders
      resources :accounts
      resources :books do
        member do
          delete :delete_image_attachment
        end
      end
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :book

  CART_PROPERTIES = %i(user_id book_id date_add quantity).freeze
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :init_cart

  def new; end

  def create
    @cart_params = params[:cart]
    cur_cart_item = @cart.map do |item|
      next item if item["book_id"] == @cart_params["book_id"].to_i
    end
    cur_cart_item.compact!
    if cur_cart_item[0].present?
      cur_cart_item[0]["quantity"] += @cart_params["quantity"].to_i
    else
      @cart << {
        "book_id": @cart_params["book_id"].to_i,
        "quantity": @cart_params["quantity"].to_i
      }
    end
    refresh
  end

  def destroy
    @cart.reject! do |item|
      item["book_id"] == params[:book_id].to_i
    end

    respond_to do |format|
      format.js{render :destroy}
    end
  end

  private
  def cart_params
    params.require(:cart).permit Cart::CART_PROPERTIES
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def total_price
    @cart.reduce(Settings.zero) do |total, item|
      total + item["quantity"] * find_book(item["book_id"]).price
    end
  end
end

app/views/carts/_cart.html.erb
<div class="container-fluid">
  <h3 class="mt-4"><%= t "cart" %></h3>
</div>
<div class="row">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered m-0">
        <thead class="bg-dark text-center text-white">
          <tr>
            <th class="py-3 px-2 col-6"><%= t "cart" %></th>
            <th class="py-3 px-2 col-2"><%= t "price" %></th>
            <th class="py-3 px-2 col-2"><%= t "quantity" %></th>
            <th class="py-3 px-2 col-2"><%= t "total" %></th>
            <th class="align-middle py-3 px-0"></th>
          </tr>
        </thead>

        <tbody class="text-center">
          <%= render partial: "carts/cart_row", collection: @cart, as: :cart %>
        </tbody>
      </table>
    </div>

    <div class="d-flex flex-row-reverse align-items-center pb-4">
      <div class="float-right">
        <% if user_signed_in? %>
          <button type="button" class="btn btn-lg btn-default md-btn-flat mt-2 mr-3">
            <%= link_to t("back"), books_path, class:"text-decoration-none" %>
          </button>
          <button type="button" class="btn btn-lg btn-primary mt-2">
            <%= link_to t("go_checkout"), checkout_path, class: "text-white text-decoration-none" %>
          </button>
        <% else %>
          <h5 class="mt-2">
            <%= t "please_login" %>
            <%= link_to t("login"), new_user_session_path, class: "text-decoration-none" %>
          </h5>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/carts/_cart_row.html.erb
<tr id="<%= "cart_#{cart["book_id"]}" %>">
  <td class="p-4">
    <div class="media align-items-center">
      <div class="card-img-actions">
        <% find_book(cart["book_id"]).images.each do |image| %>
          <%= image_tag image, class: "img-fluid img-table" %>
        <% end %>
      </div>
      <h5 class="font-weight-semibold ml-3"><%= @book.name %></h5>
    </div>
  </td>
  <td class="font-weight-semibold align-middle p-4"><%= price_format(@book.price) %></td>
  <td class="align-middle p-4">
    <div class="row">
      <%= link_to "-",
        quantity_minus_path,
        data: {params: "book_id=#{cart["book_id"]}"}, method: :put,
        remote: true, class: "btn btn-primary col mr-1"
      %>
      <input type="number" size="2" class="form-control col-5" title="Qty" value="<%= cart["quantity"] %>" min="0" disabled>
      <%= link_to "+", quantity_plus_path,
        data: {params: "book_id=#{cart["book_id"]}"}, method: :put,
        remote: true, class: "btn btn-primary col ml-1"
      %>
    </div>
  </td>
  <td class="font-weight-semibold align-middle p-4"><%= price_format(cart["quantity"]*@book.price) %></td>
  <td class="text-center align-middle">
    <%= link_to t("delete"), delete_cart_path,
      data: {params: "book_id=#{cart["book_id"]}", confirm: t("you_sure")}, method: :delete,
      remote: true, class: "btn btn-danger"
    %>
  </td>
</tr>

app/views/carts/destroy.js.erb
$("#cart_<%= params[:book_id].to_i %>").remove();
$("#flash_messages").html("<%= j render 'devise/shared/flash_notices' %>");

app/views/carts/index.html.erb
<div class="container">
  <%= render "carts/cart" %>
</div>

app/views/carts/quantity.js.erb
$(".main").html("<%= j render 'carts/cart' %>")