config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "store#home"
    get "store/home"
    get "/cart", to: "store#cart"
    post "/cart", to: "store#cart"
    get "/checkout", to: "store#checkout"
    delete "/carts", to: "carts#destroy", as: :delete_cart
    put "/minus_items", to: "minus_items#update", as: :quantity_minus
    put "/plus_items", to: "plus_items#update", as: :quantity_plus

    as :user do
      get "/login", to: "devise/sessions#new"
      post "/login", to: "devise/sessions#create"
      delete "/logout", to: "devise/sessions#destroy"
      get "/signup", to: "devise/registrations#new"
    end

    resources :categories, only: %i(show)
    resources :books, only: %i(index show)
    resources :carts, only: %i(index create)
    resources :orders, except: %i(edit)
    namespace :admin do
      resources :homes
      resources :categories
      resources :products
      resources :orders
      resources :accounts
      resources :books do
        member do
          delete :delete_image_attachment
        end
      end
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  PROPERTIES = %i(name desc).freeze

  has_many :books, dependent: :nullify

  scope :recent_add, ->{order created_at: :desc}

  validates :name, presence: true,
    length: {maximum: Settings.max_name}
  validates :desc, presence: true,
    length: {maximum: Settings.max_desc}

  ransack_alias :category, :name_or_desc
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  authorize_resource class: false

  before_action :load_category, except: %i(index new create)
  before_action :check_books, only: :destroy

  def index
    @search = Category.ransack params[:q]
    @pagy, @categories = pagy @search.result,
                              items: Settings.page_items_10
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "created"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update category_params
      flash[:success] = t "updated"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "update_failed"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "deleted"
    else
      flash[:danger] = t "delete_failed"
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit Category::PROPERTIES
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category

    flash[:danger] = t "not_found"
    redirect_to admin_categories_path
  end

  def check_books
    return if @category.books.empty?

    flash[:danger] = t "dont_move_cate"
    refresh
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_book

  def show
    @category = Category.find_by id: params[:id]
    return if @category

    flash[:error] = t "not_found"
    redirect_to root_path
  end

  private
  def load_book
    books = Book.load_book_in_category(params[:id])
    @search = books.ransack params[:q]
    @pagy, @books = pagy @search.result,
                         items: Settings.page_items_10
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def load_category
    Category.all
  end
end

app/views/categories/_category.html.erb
<div class="col-md-3 mt-2">
  <div class="card">
    <div class="card-body">
      <div class="card-img-actions">
        <% book.images.each do |image| %>
          <%= image_tag image, class: "card-img card-img-height" %>
        <% end %>
      </div>
    </div>
    <div class="card-body bg-light text-center">
      <div class="mb-2">
        <h6 class="font-weight-bold mb-2"><%= link_to book.name, book_path(book.id) %></h6> 
        <a href="#" class="text-muted" data-abc="true"><%= book.category_name %></a>
      </div>
      <h4 class="mb-0 pb-2 font-weight-semibold"><%= price_format book.price %></h4>
      <%= form_for(Cart.new, url: carts_path) do |f| %>
        <%= f.number_field :quantity, value: 1, hidden: true %>
        <%= f.number_field :book_id, value: book.id, hidden: true %>
        <%= f.submit t("store.add_to_cart"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/_form_search.html.erb
<%= search_form_for @search, url: category_path(params[:id]) do |f| %>
  <div class="d-flex form-floating">
    <%= f.text_field :book_cont, class: "form-control shadow-none" %><br>
    <label><%= t "info" %></label>
    <%= f.submit t("search"), class: "btn btn-primary search-btn" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<div class="container mt-50 mb-50">
  <h4 class="mt-4"><%= t "category" %>: <%= @category.name %></h4>
  <div class="row mb-4">
    <%= render "form_search" %>
    <%= render partial: "category", collection: @books, as: :book %>
  </div>
  <%== pagy_bootstrap_nav @pagy %>
</div>